### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by elxris** [javierbyte/javierbyte.github.io#3]
Qué modelo sun tus audífonos bluetooth bosé?

**Comment by javierbyte** [comment]
@elxris Bose QC35 https://www.amazon.com.mx/Bose-759944-0010-Quietcomfort-Adífonos-inalámbricos/dp/B01E3SNO1G/ref=sr_1_1?ie=UTF8&qid=1477970952&sr=8-1&keywords=bose+qc+35

**Comment by elxris** [comment]
jajaja, gracias. 👍
